// Generated by art/tools/scale_sheet.py from art/ai/sign_r_raw.png - don't edit.
#ifndef _GEN_SIGN_R_H_
#define _GEN_SIGN_R_H_

#define SIGN_R_LEVELS 10
// per size (smallest first): top row in art/sign_r_sheet.png, width, height
static const struct { unsigned short y, w, h; } g_pSign_rLevel[10] = {
	{0, 3, 3},
	{3, 4, 3},
	{6, 5, 4},
	{10, 7, 6},
	{16, 9, 8},
	{24, 12, 10},
	{34, 16, 14},
	{48, 22, 19},
	{67, 30, 25},
	{92, 40, 34},
};

#endif
