// Generated by art/tools/scale_sheet.py from art/ai/gate_raw.png - don't edit.
#ifndef _GEN_GATE_H_
#define _GEN_GATE_H_

#define GATE_LEVELS 10
// per size (smallest first): top row in art/gate_sheet.png, width, height
static const struct { unsigned short y, w, h; } g_pGateLevel[10] = {
	{0, 2, 7},
	{7, 3, 10},
	{17, 4, 13},
	{30, 5, 17},
	{47, 7, 24},
	{71, 9, 32},
	{103, 12, 42},
	{145, 17, 57},
	{202, 22, 77},
	{279, 30, 103},
};

#endif
