// Generated by art/tools/scale_sheet.py from art/ai/rival_raw.png - don't edit.
#ifndef _GEN_RIVAL_H_
#define _GEN_RIVAL_H_

#define RIVAL_LEVELS 10
// per size (smallest first): top row in art/rival_sheet.png, width, height
static const struct { unsigned short y, w, h; } g_pRivalLevel[10] = {
	{0, 4, 3},
	{3, 5, 3},
	{6, 6, 4},
	{10, 9, 6},
	{16, 12, 8},
	{24, 15, 10},
	{34, 21, 14},
	{48, 28, 19},
	{67, 38, 25},
	{92, 50, 34},
};

#endif
