// Generated by art/tools/scale_sheet.py from art/ai/bush_raw.png - don't edit.
#ifndef _GEN_BUSH_H_
#define _GEN_BUSH_H_

#define BUSH_LEVELS 10
// per size (smallest first): top row in art/bush_sheet.png, width, height
static const struct { unsigned short y, w, h; } g_pBushLevel[10] = {
	{0, 3, 3},
	{3, 4, 3},
	{6, 5, 3},
	{9, 7, 4},
	{13, 10, 5},
	{18, 13, 6},
	{24, 18, 9},
	{33, 24, 12},
	{45, 32, 16},
	{61, 43, 21},
};

#endif
