// Generated by art/tools/scale_sheet.py from art/ai/palm_raw.png - don't edit.
#ifndef _GEN_PALM_H_
#define _GEN_PALM_H_

#define PALM_LEVELS 10
// per size (smallest first): top row in art/palm_sheet.png, width, height
static const struct { unsigned short y, w, h; } g_pPalmLevel[10] = {
	{0, 3, 6},
	{6, 4, 8},
	{14, 5, 10},
	{24, 7, 14},
	{38, 9, 19},
	{57, 13, 25},
	{82, 17, 34},
	{116, 23, 46},
	{162, 31, 62},
	{224, 41, 83},
};

#endif
