#!/usr/bin/env python3
"""Draws art/backdrop.txt: the horizon strip behind the road (distant snowy
mountains, green hills in front), 512 px wide so it loops, 32 rows. It uses
the road's colours (see art/art.toml): . sky (transparent), M/m mountain
light/shade, S snow, H/h hills. Deterministic: rerun after tweaking.

    python3 art/tools/backdrop.py
"""
import math
import os
import random

W, H = 512, 32
rnd = random.Random(1987)


def wrapd(x, cx):
    d = x - cx
    return (d + W // 2) % W - W // 2        # signed distance, wrapping around


def jag(n, amp):
    """A looping bumpy offset: a smoothed random walk, +-amp px."""
    v, out = 0.0, []
    for _ in range(W):
        v = v * 0.85 + rnd.uniform(-1, 1)
        out.append(v)
    m = max(abs(o) for o in out) or 1
    return [o / m * amp for o in out]


# Mountains: triangular peaks (steep, not round), each lit from the left
peaks = [(rnd.randrange(W), rnd.randint(14, 28), rnd.randint(34, 70)) for _ in range(7)]
mj = jag(W, 1.6)
height, lit = [0.0] * W, [True] * W
for x in range(W):
    best, side = 0.0, True
    for cx, h, w in peaks:
        d = wrapd(x, cx)
        v = h - abs(d) * h / w
        if v > best:
            best, side = v, d <= 0
    height[x], lit[x] = best + mj[x] if best > 0 else 0, side
# Hills: low rolling green in front
hj = jag(W, 1.0)
hills = [5 + 3 * math.sin(2 * math.pi * x / W * 5) + 2 * math.sin(2 * math.pi * x / W * 11 + 1) + hj[x]
         for x in range(W)]
snowline = [17 + j for j in jag(W, 1.5)]
rows = [['.'] * W for _ in range(H)]
for x in range(W):
    top = H - int(round(height[x]))
    for y in range(max(0, top), H):
        above = H - y                            # height of this pixel
        if height[x] > snowline[x] + 1 and above > snowline[x]:
            rows[y][x] = 'S'
        else:
            rows[y][x] = 'M' if lit[x] else 'm'
    htop = H - int(round(hills[x]))
    for y in range(max(0, htop), H):
        rows[y][x] = 'h' if (y - htop) < 2 else 'H'
path = os.path.join(os.path.dirname(__file__), '..', 'backdrop.txt')
with open(path, 'w') as f:
    f.write('# Generated by art/tools/backdrop.py - edit that, not this.\n')
    f.write('colors\n  .  transparent\n  H  0x4A2\n  h  0x391\n  S  0xEEE\n  M  0x889\n  m  0x778\nframe\n')
    f.write('\n'.join(''.join(r) for r in rows) + '\n')
print('wrote', os.path.normpath(path))
