#!/usr/bin/env python3
"""The HUD font: 5x7 arcade letters drawn here as text, each in an 8x8 cell
with a black shadow one pixel right and down. Writes src/gen_font.h: per
character two bytes per row (plane 0 = letter or shadow, plane 1 = letter),
so a letter comes out in colour 3 (yellow) on colour 1 (black) - the HUD
draws straight into playfield 1's top lines.

    python3 art/tools/font.py
"""
import os

GLYPHS = {
    ' ': [''] * 7,
    '0': [' ### ', '#   #', '#  ##', '# # #', '##  #', '#   #', ' ### '],
    '1': ['  #  ', ' ##  ', '  #  ', '  #  ', '  #  ', '  #  ', ' ### '],
    '2': [' ### ', '#   #', '    #', '  ## ', ' #   ', '#    ', '#####'],
    '3': ['#### ', '    #', '    #', ' ### ', '    #', '    #', '#### '],
    '4': ['   # ', '  ## ', ' # # ', '#  # ', '#####', '   # ', '   # '],
    '5': ['#####', '#    ', '#### ', '    #', '    #', '#   #', ' ### '],
    '6': ['  ## ', ' #   ', '#    ', '#### ', '#   #', '#   #', ' ### '],
    '7': ['#####', '    #', '   # ', '  #  ', ' #   ', ' #   ', ' #   '],
    '8': [' ### ', '#   #', '#   #', ' ### ', '#   #', '#   #', ' ### '],
    '9': [' ### ', '#   #', '#   #', ' ####', '    #', '   # ', ' ##  '],
    'A': [' ### ', '#   #', '#   #', '#####', '#   #', '#   #', '#   #'],
    'B': ['#### ', '#   #', '#   #', '#### ', '#   #', '#   #', '#### '],
    'C': [' ### ', '#   #', '#    ', '#    ', '#    ', '#   #', ' ### '],
    'D': ['#### ', '#   #', '#   #', '#   #', '#   #', '#   #', '#### '],
    'E': ['#####', '#    ', '#    ', '#### ', '#    ', '#    ', '#####'],
    'F': ['#####', '#    ', '#    ', '#### ', '#    ', '#    ', '#    '],
    'G': [' ### ', '#   #', '#    ', '# ###', '#   #', '#   #', ' ####'],
    'H': ['#   #', '#   #', '#   #', '#####', '#   #', '#   #', '#   #'],
    'I': [' ### ', '  #  ', '  #  ', '  #  ', '  #  ', '  #  ', ' ### '],
    'J': ['  ###', '   # ', '   # ', '   # ', '   # ', '#  # ', ' ##  '],
    'K': ['#   #', '#  # ', '# #  ', '##   ', '# #  ', '#  # ', '#   #'],
    'L': ['#    ', '#    ', '#    ', '#    ', '#    ', '#    ', '#####'],
    'M': ['#   #', '## ##', '# # #', '# # #', '#   #', '#   #', '#   #'],
    'N': ['#   #', '#   #', '##  #', '# # #', '#  ##', '#   #', '#   #'],
    'O': [' ### ', '#   #', '#   #', '#   #', '#   #', '#   #', ' ### '],
    'P': ['#### ', '#   #', '#   #', '#### ', '#    ', '#    ', '#    '],
    'Q': [' ### ', '#   #', '#   #', '#   #', '# # #', '#  # ', ' ## #'],
    'R': ['#### ', '#   #', '#   #', '#### ', '# #  ', '#  # ', '#   #'],
    'S': [' ####', '#    ', '#    ', ' ### ', '    #', '    #', '#### '],
    'T': ['#####', '  #  ', '  #  ', '  #  ', '  #  ', '  #  ', '  #  '],
    'U': ['#   #', '#   #', '#   #', '#   #', '#   #', '#   #', ' ### '],
    'V': ['#   #', '#   #', '#   #', '#   #', '#   #', ' # # ', '  #  '],
    'W': ['#   #', '#   #', '#   #', '# # #', '# # #', '# # #', ' # # '],
    'X': ['#   #', '#   #', ' # # ', '  #  ', ' # # ', '#   #', '#   #'],
    'Y': ['#   #', '#   #', ' # # ', '  #  ', '  #  ', '  #  ', '  #  '],
    'Z': ['#####', '    #', '   # ', '  #  ', ' #   ', '#    ', '#####'],
    '!': ['  #  ', '  #  ', '  #  ', '  #  ', '  #  ', '     ', '  #  '],
    '/': ['    #', '    #', '   # ', '  #  ', ' #   ', '#    ', '#    '],
    ':': ['     ', '  #  ', '  #  ', '     ', '  #  ', '  #  ', '     '],
    '.': ['     ', '     ', '     ', '     ', '     ', ' ##  ', ' ##  '],
    '-': ['     ', '     ', '     ', '#####', '     ', '     ', '     '],
}

here = os.path.dirname(os.path.abspath(__file__))
chars = ''.join(GLYPHS)
out = ['// Generated by art/tools/font.py - don\'t edit.', '#ifndef _GEN_FONT_H_', '#define _GEN_FONT_H_', '',
       f'#define FONT_CHARS "{chars}"',
       f'#define FONT_COUNT {len(chars)}',
       '// per character, per row: plane 0 (letter | shadow), plane 1 (letter)',
       f'static const unsigned char g_pFont[{len(chars)}][8][2] = {{']
for c in chars:
    rows = [r.ljust(5) for r in GLYPHS[c]]
    assert len(rows) == 7, c
    fill = [[0] * 8 for _ in range(8)]
    for y, r in enumerate(rows):
        for x, p in enumerate(r):
            if p == '#':
                fill[y][x + 1] = 1          # one column of margin on the left
    body = []
    for y in range(8):
        p0 = p1 = 0
        for x in range(8):
            letter = fill[y][x]
            shadow = x > 0 and y > 0 and fill[y - 1][x - 1]
            bit = 0x80 >> x
            if letter:
                p0 |= bit
                p1 |= bit
            elif shadow:
                p0 |= bit
        body.append(f'{{0x{p0:02X}, 0x{p1:02X}}}')
    out.append(f'\t{{{", ".join(body)}}},   // {c!r}')
out += ['};', '', '#endif', '']
with open(os.path.join(here, '..', '..', 'src', 'gen_font.h'), 'w') as f:
    f.write('\n'.join(out))
print(f'{len(chars)} characters')
